// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["pi/Pi"], function(aPi) {
  var Button;
  return Button = (function(superClass) {
    extend(Button, superClass);

    function Button() {
      return Button.__super__.constructor.apply(this, arguments);
    }

    Button.prototype.attr = function() {
      return Button.__super__.attr.apply(this, arguments).concat(["target", "click"]);
    };

    Button.prototype.init = function() {
      if (this.a.click) {
        this.rpc(this.a.target, this.e.data(), (function() {}));
      }
      return this.e.click((function(_this) {
        return function(ev) {
          ev.preventDefault();
          return _this.rpc(_this.a.target, [_this.e.data()], function() {});
        };
      })(this));
    };

    return Button;

  })(aPi);
});
