// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["pi/Pi"], function(P) {
  var aClick, _ref;
  return aClick = (function(_super) {
    __extends(aClick, _super);

    function aClick() {
      _ref = aClick.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    aClick.prototype.attr = function() {
      return aClick.__super__.attr.apply(this, arguments).concat(["target"]);
    };

    aClick.prototype.init = function() {
      var _this = this;
      return this.e.click(function(ev) {
        ev.preventDefault();
        return _this.click();
      });
    };

    aClick.prototype.click = function() {
      return this.rpc(this.a.target, [this.data]);
    };

    return aClick;

  })(P);
});
