// Generated by CoffeeScript 1.10.0
define([], function() {
  var CSSInjector;
  return CSSInjector = (function() {
    CSSInjector.prototype.css = null;

    function CSSInjector() {
      this.css = {};
    }

    CSSInjector.prototype.injectCSS = function(uri) {
      var link;
      if (this.css[uri]) {
        return;
      } else {
        this.css[uri] = 1;
      }
      link = document.createElement("link");
      link.type = "text/css";
      link.rel = "stylesheet";
      link.href = uri;
      return document.getElementsByTagName("head")[0].appendChild(link);
    };

    return CSSInjector;

  })();
});
