// Generated by CoffeeScript 1.10.0
var extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
  hasProp = {}.hasOwnProperty;

define(["pi/Pi"], function(aPi) {
  var aForm;
  return aForm = (function(superClass) {
    extend(aForm, superClass);

    function aForm() {
      return aForm.__super__.constructor.apply(this, arguments);
    }

    aForm.prototype.attr = function() {
      return aForm.__super__.attr.apply(this, arguments).concat(["el", "target"]);
    };

    aForm.prototype.serialize = function(inputs) {
      var _i, fn, j, len, ret;
      if (inputs == null) {
        inputs = $(this.a.el);
      }
      ret = {};
      fn = function(i) {
        var group, item_val, tmp;
        group = i.data("group") || "form";
        if (!ret[group]) {
          ret[group] = [];
        }
        if (i.attr("type") === "checkbox") {
          if (i.prop("checked")) {
            return ret[group].push({
              name: i.attr("name"),
              value: true
            });
          } else {
            return ret[group].push({
              name: i.attr("name"),
              value: false
            });
          }
        } else if (i.attr("type") === "radio") {
          if (i.prop("checked")) {
            return ret[group].push({
              name: i.attr("name"),
              value: i.attr("value"),
              "class": i.attr("class")
            });
          }
        } else {
          tmp = {
            name: i.attr("id"),
            value: i.val()
          };
          if (i.attr("item_map")) {
            item_val = i.attr("item_val");
            ret[group].push({
              name: i.attr("item_map"),
              "class": i.attr("class"),
              value: item_val === "null" ? null : item_val
            });
          }
          return ret[group].push(tmp);
        }
      };
      for (j = 0, len = inputs.length; j < len; j++) {
        _i = inputs[j];
        fn($(_i));
      }
      return ret;
    };

    aForm.prototype.deserialize = function(data) {
      var _i, hdata, inputs, j, len, results;
      inputs = $(this.a.el);
      hdata = data;
      results = [];
      for (j = 0, len = inputs.length; j < len; j++) {
        _i = inputs[j];
        results.push((function(i) {
          var f;
          if (i.attr("type") === "checkbox" && hdata[i.attr("id")]) {
            return i.attr("checked", 1);
          } else {
            if (f = hdata[i.attr("id")]) {
              return i.val(f);
            }
          }
        })($(_i)));
      }
      return results;
    };

    aForm.prototype.reset = function(inputs) {
      var _i, j, len, results;
      if (inputs == null) {
        inputs = $(this.a.el);
      }
      results = [];
      for (j = 0, len = inputs.length; j < len; j++) {
        _i = inputs[j];
        results.push((function(i) {
          if (i.attr("type") === "checkbox") {
            return i.removeAttr("checked");
          } else {
            if (i.attr("item_map")) {
              i.attr("item_val", "");
            }
            return i.val("");
          }
        })($(_i)));
      }
      return results;
    };

    aForm.prototype.init = function() {
      aForm.__super__.init.apply(this, arguments);
      return this.e.click((function(_this) {
        return function(ev) {
          return _this.onClick(ev);
        };
      })(this));
    };

    aForm.prototype.save = function() {
      var data;
      data = this.serialize();
      return this.rpc(this.a.target, [data.form], function() {});
    };

    aForm.prototype.onClick = function(ev) {
      var data;
      ev.preventDefault();
      data = this.serialize();
      return this.rpc(this.a.target, [data.form, this], function() {});
    };

    return aForm;

  })(aPi);
});
