// Generated by CoffeeScript 1.6.2
require(["../conf/requirejs"], function(Conf) {
  require.config(Conf);
  return require(["router", "lib/jquery"], function(Router, JQuery) {
    var router;
    return router = new Router;
  });
});
