// Generated by CoffeeScript 1.10.0
var slice = [].slice;

define(["conf/logger"], function(Conf) {
  var Logger;
  return Logger = (function() {
    Logger.prototype.sys_debug = function() {};

    Logger.prototype.sys_error = function() {};

    Logger.prototype.debug = function() {
      var args, module;
      module = arguments[0], args = 2 <= arguments.length ? slice.call(arguments, 1) : [];
      if ((Conf[module] == null) || Conf[module]) {
        return this.sys_debug.apply(this, arguments);
      }
    };

    Logger.prototype.err = function() {
      var err;
      this.sys_error.apply(this, arguments);
      err = new Error('');
      return this.sys_debug(err.stack);
    };

    function Logger() {
      if (window.console && Function.prototype.bind && (typeof console.log === "object" || typeof console.log === "function")) {
        this.sys_debug = Function.prototype.bind.call(console.log, console);
        this.sys_error = Function.prototype.bind.call(console.error, console);
      }
      window.onerror = (function(_this) {
        return function(msg, url, line) {
          return _this.err("onerror()", url, msg, line);
        };
      })(this);
    }

    return Logger;

  })();
});
