// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["pi/Pi"], function(P) {
  var aPost, _ref;
  return aPost = (function(_super) {
    __extends(aPost, _super);

    function aPost() {
      _ref = aPost.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    aPost.prototype.attr = function() {
      return aPost.__super__.attr.apply(this, arguments).concat(["uri"]);
    };

    aPost.prototype.send = function(p) {
      return this.ppost(this.a.uri, p);
    };

    return aPost;

  })(P);
});
