// Generated by CoffeeScript 1.6.2
define([], function() {
  var aPromise;
  return aPromise = (function() {
    function aPromise() {}

    aPromise.prototype.defer = null;

    aPromise.prototype.next = null;

    aPromise.prototype.r = null;

    aPromise.prototype.state = false;

    aPromise.prototype.done = function(r) {
      this.r = r;
      return this.state = true;
    };

    aPromise.prototype.success = function(r) {
      var res;
      this.done(r);
      if (this.defer) {
        res = this.defer(r);
        if (this.next) {
          return this.next.success(res);
        }
      }
    };

    aPromise.prototype.then = function(defer) {
      this.defer = defer;
      this.next = new aPromise();
      if (this.state) {
        this.next.done(this.defer(r));
      }
      return this.next;
    };

    return aPromise;

  })();
});
