// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["a/Pi"], function(aPi) {
  var Table, _ref;
  return Table = (function(_super) {
    __extends(Table, _super);

    function Table() {
      _ref = Table.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Table.prototype.r = null;

    Table.prototype.attr = function() {
      return Table.__super__.attr.apply(this, arguments).concat(["uri"]);
    };

    Table.prototype.get_r = function() {
      return this.r;
    };

    Table.prototype.get_id = function() {
      return this.e.attr('id');
    };

    Table.prototype.page = function(page) {
      return this.load({
        page: page
      });
    };

    Table.prototype.load = function(p) {
      var _this = this;
      return this.post(this.a.uri, p, function(r) {
        _this.r = r;
        return _this.event("data", r);
      });
    };

    return Table;

  })(aPi);
});
