// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["a/Pi", "lib/jquery-ui"], function(P) {
  var aDialog, _ref;
  return aDialog = (function(_super) {
    __extends(aDialog, _super);

    function aDialog() {
      _ref = aDialog.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    aDialog.prototype.init = function() {
      var _this = this;
      return this.e.dialog({
        close: function(ev, ui) {
          return _this.e.remove();
        },
        draggable: true,
        width: this.data.width || 500,
        height: this.data.height || "auto"
      });
    };

    aDialog.prototype.close = function() {
      return this.e.remove();
    };

    return aDialog;

  })(P);
});
