// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["a/Pi"], function(P) {
  var aFwd, _ref;
  return aFwd = (function(_super) {
    __extends(aFwd, _super);

    function aFwd() {
      _ref = aFwd.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    aFwd.prototype.attr = function() {
      return aFwd.__super__.attr.apply(this, arguments).concat(["uri"]);
    };

    aFwd.prototype.go = function() {
      return window.location = this.a.uri;
    };

    return aFwd;

  })(P);
});
