// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["a/Pi"], function(aPi) {
  var TableNav, _ref;
  return TableNav = (function(_super) {
    __extends(TableNav, _super);

    function TableNav() {
      _ref = TableNav.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    TableNav.prototype.attr = function() {
      return TableNav.__super__.attr.apply(this, arguments).concat(["bind", "name"]);
    };

    TableNav.prototype.init = function() {
      var _this = this;
      return this.e.click(function(ev) {
        ev.preventDefault();
        return _this.rpc_to(_this.a.bind, "nav", [_this.a.name], function() {});
      });
    };

    return TableNav;

  })(aPi);
});
