// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["a/Ed/CodeMirror", "lib/codemirror/mode/htmlmixed/htmlmixed"], function(P) {
  var EdHTML, _ref;
  return EdHTML = (function(_super) {
    __extends(EdHTML, _super);

    function EdHTML() {
      _ref = EdHTML.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    EdHTML.prototype.init = function() {
      this.a.mode = "htmlmixed";
      return EdHTML.__super__.init.apply(this, arguments);
    };

    return EdHTML;

  })(P);
});
