// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["a/Ed/CodeMirror", "lib/codemirror/mode/jade/jade"], function(P) {
  var EdJade, _ref;
  return EdJade = (function(_super) {
    __extends(EdJade, _super);

    function EdJade() {
      _ref = EdJade.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    EdJade.prototype.init = function() {
      this.a.mode = "jade";
      return EdJade.__super__.init.apply(this, arguments);
    };

    EdJade.prototype.process = function(text) {
      var _this = this;
      return this.post("r/compile", {
        text: text,
        type: "Jade"
      }, function(r) {
        _this.e.html(r.compiled);
        return _this.rt.pi(_this.e);
      });
    };

    return EdJade;

  })(P);
});
