// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["a/Ed/CodeMirror", "lib/textile"], function(P, Textile) {
  var EdTextile, _ref;
  return EdTextile = (function(_super) {
    __extends(EdTextile, _super);

    function EdTextile() {
      _ref = EdTextile.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    EdTextile.prototype.init = function() {
      this.a.mode = "textile";
      return EdTextile.__super__.init.apply(this, arguments);
    };

    EdTextile.prototype.process = function(text) {
      this.e.html(Textile.convert(text));
      return this.rt.pi(this.e);
    };

    return EdTextile;

  })(P);
});
