// Generated by CoffeeScript 1.6.2
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(["a/Pi"], function(aPi) {
  var aTablePager, _ref;
  return aTablePager = (function(_super) {
    __extends(aTablePager, _super);

    function aTablePager() {
      _ref = aTablePager.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    aTablePager.prototype.page = 0;

    aTablePager.prototype.page_count = 0;

    aTablePager.prototype.key = 'page';

    aTablePager.prototype.attr = function() {
      return aTablePager.__super__.attr.apply(this, arguments).concat(["bind", "name"]);
    };

    aTablePager.prototype.init = function() {
      var _this = this;
      this.subscribe(this.a.bind, "data", function(rs) {
        return _this.set(rs);
      });
      this.rpc_to(this.a.bind, "get_id", [], function(key) {
        _this.key = key;
        return console.log(_this.key);
      });
      this.rpc_to(this.a.bind, "page", [this.get_page() - 1], function() {});
      return this.rpc_to(this.a.bind, "get_r", [], function(rs) {
        if (rs) {
          return _this.set(rs);
        }
      });
    };

    aTablePager.prototype.set_page_to_uri = function() {
      var new_uri, old_uri, p;
      old_uri = this.rt.uri.search();
      p = this.rt.uri.search(true);
      p[this.key] = 1 + this.page;
      this.rt.uri.search(p);
      new_uri = this.rt.uri.search();
      if (old_uri !== new_uri) {
        return this.rt.set_uri_without_event(this.rt.uri);
      }
    };

    aTablePager.prototype.notify = function() {
      return this.rpc_to(this.a.bind, "page", [this.page], (function() {}));
    };

    aTablePager.prototype.get_page = function() {
      return this.rt.uri.search(true)[this.key];
    };

    aTablePager.prototype.forward = function(n) {
      this.page = this.page + n >= this.page_count ? this.page_count - 1 : this.page + n;
      this.set_page_to_uri();
      return this.notify();
    };

    aTablePager.prototype.backward = function(n) {
      this.page = this.page - n < 0 ? 0 : this.page - n;
      this.set_page_to_uri();
      return this.notify();
    };

    aTablePager.prototype.nav = function(name) {
      switch (name) {
        case "forward":
          return this.forward(1);
        case "fastforward":
          return this.forward(10);
        case "back":
          return this.backward(1);
        case "fastback":
          return this.backward(10);
      }
    };

    aTablePager.prototype.set = function(pager) {
      this.tmpl = this.rt.source(this.a.name);
      this.page = pager.page;
      this.page_count = pager.page_count;
      this.set_page_to_uri();
      this.e.html(this.tmpl({
        e: this,
        pager: {
          page: this.page + 1,
          page_count: this.page_count
        }
      }));
      return this.rt.pi(this.e);
    };

    return aTablePager;

  })(aPi);
});
