// Generated by CoffeeScript 1.6.2
define(["lib/doT"], function(doT) {
  var mSource;
  return mSource = (function() {
    mSource.registry = {};

    mSource.get = function(name) {
      if (mSource.registry[name]) {
        return mSource.registry[name];
      } else {
        return null;
      }
    };

    function mSource(name, text) {
      mSource.registry[name] = doT.template(text);
    }

    return mSource;

  }).call(this);
});
